version: 2

jobs:
  publish-docker-image:
    working_directory: ~/repo
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build & push image
          command: |
            export VERSION=$CIRCLE_SHA1
            echo 'Building version' $VERSION
            docker build -t computesoftware/datomic-socks-proxy:$VERSION .
            docker push computesoftware/datomic-socks-proxy:$VERSION

workflows:
  version: 2
  ci-workflow:
    jobs:
      - publish-docker-image:
          context: docker-env
          filters:
            branches:
              only:
                - master